### ISSUE TITLE
helmchart 3.4.1 installs 3.4.0

### ISSUE THREAD

**Issue by jonasbartho** [joe-elliott/cert-exporter#149]
Hi,

When I do a helm install towards version `3.4.1`, I see it actually uses `3.4.0`.
Can this be fixed? :)

**Comment by joe-elliott** [comment]
The latest helm chart is 3.4.1. The latest version of cert-exporter is 2.11.1.

I'm not sure what's happening if installing helm chart 3.4.0 actually installs 3.4.1. Can you give more details?

**Comment by jonasbartho** [comment]
Hi @joe-elliott 

When I for example want to install cert-exporter with helm chart version `3.4.1`, I see it actually installs helm chart version `3.4.0`

I have verified this behaviour in 2 ways:

1. way was through `kustomize`... I have had `3.4.0` running in production for multiple months and wanted to upgrade to helm chart `3.4.1` but nothing happens, which means it cannot detect new changes:
```yaml
helmCharts:
  - name: cert-exporter
    releaseName: cert-exporter
    repo: https://joe-elliott.github.io/cert-exporter/
    version: 3.4.1
    namespace: openshift-monitoring
    valuesInline:
      dashboards:
        certManagerDashboard:
          create: false
```
2. I have also tried to apply `3.4.1` directly to a new k8s-cluster, but I see it just applies:
```
      app.kubernetes.io/version: v2.11.0
      helm.sh/chart: cert-exporter-3.4.0
```

Here I installed cert-exporter through the same commands as what is documented in your README:
```
helm repo add cert-exporter https://joe-elliott.github.io/cert-exporter/
helm repo update
helm upgrade --install cert-exporter cert-exporter/cert-exporter

```
To me it looks like helm cannot detect version `3.4.1`?
