### ISSUE TITLE
User cannot list resource secrets in API group "" at the cluster scope

### ISSUE THREAD

**Issue by AmetPreply** [joe-elliott/cert-exporter#17]
Hi.
I've applied this manifest from the docs:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cert-exporter
  name: cert-exporter
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: cert-exporter
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        name: cert-exporter
    spec:
      serviceAccountName: cert-exporter
      containers:
      - image: joeelliott/cert-exporter:v2.0.0
        name: cert-exporter
        command: ["./app"]
        args:
        - --secrets-annotation-selector='cert-manager.io/certificate-name'
        - --secrets-include-glob='*.crt'
        - --alsologtostderr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-exporter
subjects:
- kind: ServiceAccount
  name: cert-exporter
  namespace: default
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-exporter
  namespace: kube-system
```

There are some issues in pod's log:

```
$ kc logs cert-exporter-65956cb7c6-sv844
I0403 07:19:43.229744       1 main.go:53] Application Starting
I0403 07:19:43.232963       1 periodicSecretChecker.go:60] Begin periodic check
E0403 07:19:43.248757       1 periodicSecretChecker.go:86] Error requesting secrets secrets is forbidden: User "system:serviceaccount:kube-system:cert-exporter" cannot list resource "secrets" in API group "" at the cluster scope
...
```

Have you ever struggled with that? Thanks.

Kubernetes: 1.13.12
