### ISSUE TITLE
Single metric available - cert_exporter_error_total

### ISSUE THREAD

**Issue by cloudpea** [joe-elliott/cert-exporter#33]
The only metric available in the metrics endpoint of cert-exporter is - cert_exporter_error_total

Running version v2.3.0 and the endpoint is showing as up in Prometheus.

<img width="1423" alt="Screenshot 2020-04-28 at 18 21 49" src="https://user-images.githubusercontent.com/47475230/80517569-2f8e6580-897d-11ea-9cc1-b0d4c7c062a6.png">

Also confirmed this is the only available metric by manually curling the metrics endpoint.

See full kubernetes manifest file below:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-exporter
  namespace: kube-monitoring
  labels:
    app: cert-exporter
spec:
  selector:
    matchLabels:
      name: cert-exporter
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        name: cert-exporter
        app: cert-exporter
    spec:
      serviceAccountName: cert-exporter
      containers:
      - image: joeelliott/cert-exporter:v2.3.0
        name: cert-exporter
        command: ["./app"]
        args:
        - --secrets-annotation-selector='cert-manager.io/certificate-name'
        - --secrets-include-glob='*.crt'
        - --alsologtostderr
        resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cert-exporter-metrics
  namespace: kube-monitoring
  labels:
    app: cert-exporter-metrics
spec:
  selector:
    app: cert-exporter
  ports:
    - name: metrics
      port: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-cert-exporter
  namespace: kube-monitoring
  labels:
    app: prometheus-operator-operator
    prometheus: prometheus-operator-prometheus
    release: prometheus-operator
spec:
  endpoints:
  - port: metrics
    path: /metrics
    interval: 20s
  jobLabel: cert-exporter-metrics
  namespaceSelector:
    matchNames:
    - kube-monitoring
  selector:
    matchLabels:
      app: cert-exporter-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-exporter
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-exporter
subjects:
- kind: ServiceAccount
  name: cert-exporter
  namespace: kube-monitoring
roleRef:
  kind: ClusterRole
  name: cert-exporter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-exporter
  namespace: kube-monitoring
```
