### ISSUE TITLE
how to debug exporter?

### ISSUE THREAD

**Issue by jitendrachopra** [joe-elliott/cert-exporter#50]
There is no error exporter logs but still i don't see all metrics of certificate exporter. i am not sure what i am missing so want to turn on debugger. is there a way?

```text
jichopra-macOS:prometheus-monitoring-Fork jichopra$ kubectl logs cert-exporter-5bc895c76f-5rlw9 
I0914 22:47:43.893219       1 main.go:60] Starting cert-exporter (version unknown; commit unknown; date unknown)
I0914 22:47:43.894582       1 periodicSecretChecker.go:59] Begin periodic check
I0914 22:47:43.924293       1 periodicSecretChecker.go:89] Reviewing secret cert-exporter-token-fb6v6 in default
I0914 22:47:43.924311       1 periodicSecretChecker.go:89] Reviewing secret default-token-k2ggh in default
I0914 22:47:43.924315       1 periodicSecretChecker.go:89] Reviewing secret default-token-f87sh in kube-node-lease
I0914 22:47:43.924319       1 periodicSecretChecker.go:89] Reviewing secret default-token-mcd7z in kube-public
I0914 22:47:43.924322       1 periodicSecretChecker.go:89] Reviewing secret attachdetach-controller-token-f56sj in kube-
````

metrics endpoint:

```test
# HELP cert_exporter_error_total Cert Exporter Errors
# TYPE cert_exporter_error_total counter
cert_exporter_error_total 0
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 1.0675e-05
go_gc_duration_seconds{quantile="0.25"} 1.346e-05
go_gc_duration_seconds{quantile="0.5"} 2.5262e-05
go_gc_duration_seconds{quantile="0.75"} 2.5526e-05
go_gc_duration_seconds{quantile="1"} 3.4061e-05
go_gc_duration_seconds_sum 0.000148167
go_gc_duration_seconds_count 7
```

**Comment by joe-elliott** [comment]
This is the line that is logging that the secrets are being reviewed:

https://github.com/joe-elliott/cert-exporter/blob/master/src/checkers/periodicSecretChecker.go#L89

This line is never logged:

https://github.com/joe-elliott/cert-exporter/blob/master/src/checkers/periodicSecretChecker.go#L106

So that suggests that you have annotation selectors that are not being matched.  I would review your annotation selectors and the annotations on your secrets.

**Comment by jitendrachopra** [comment]
Thanks for response. I have annotation defined. what  i am missing? 
note : i have deployed below config on default namespace. prometheus is scrapping at namespace level.
do i need to make any adjustment so prometheus can listen at default namespace level?

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cert-exporter
  name: cert-exporter
spec:
  selector:
    matchLabels:
      name: cert-exporter
  template:
    metadata:
      **annotations**:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        name: cert-exporter
    spec:
      serviceAccountName: cert-exporter
      containers:
        - image: joeelliott/cert-exporter:v2.3.2
          name: cert-exporter
          command: ["./app"]
          args:
            - --secrets-annotation-selector=cert-manager.io/certificate-name
            - --secrets-include-glob=*
            - --logtostderr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-exporter
subjects:
  - kind: ServiceAccount
    name: cert-exporter
    namespace: default
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-exporter
```

**Comment by joe-elliott** [comment]
What annotations are on the cert that you want to `cert-exporter` to parse?

**Comment by jitendrachopra** [comment]
thanks Joe. it was working after removing following annotations. my secrects didn't have any annotations.
`kubectl describe secret secretname`
`  - --secrets-annotation-selector=cert-manager.io/certificate-name`
i want to run cert-exporter on namespace.

1. running cert-exporter in default namespace.
exporter able to fetch metrics but prometheus (running on namespace) get 401 error while scrapping metrics.

`yaml
- job_name: cert-exporter
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - default`

Error:
`level=error ts=2020-09-25T23:23:18.506Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:261: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:prometheusdevor2:prometheus-prometheusdevor2\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
level=error ts=2020-09-25T23:23:18.507Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:prometheusdevor2:prometheus-prometheusdevor2\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
`
2. running cert-exporter on namespace
no error but it doesn't get metrics loaded. it seems it is not able to read certificate.
`yaml
- job_name: cert-exporter
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - prometheusdevor2
`

**Comment by joe-elliott** [comment]
I've used the prometheus operator some, but honestly don't know a ton about it.  If you need help using it I'd refer you to their documentation/help channels.

**Comment by jitendrachopra** [comment]
i think i had different kubernetes version that's why above prometheus-operator didn't work. now it is working fine.

config
``` yaml
      serviceAccountName: cert-exporter
      containers:
        - image: joeelliott/cert-exporter:v2.3.2
          name: cert-exporter
          command: ["./app"]
          args:
            **- --secrets-include-glob=*
            - --include-kubeconfig-glob=*
            - --include-cert-glob=***
            - --logtostderr
```
But i am not able to see below metrics. 

1. cert_exporter_kubeconfig_expires_in_seconds
2. cert_exporter_cert_expires_in_seconds

![Uploading Screen Shot 2020-09-27 at 8.37.04 PM.png…]()

cert exporter logs:
I0928 03:21:39.057695       1 periodicSecretChecker.go:138] Publishing node-exporter-token-86977/prometheusdevor2 metrics token
E0928 03:21:39.057700       1 periodicSecretChecker.go:141] Error exporting secret Failed to parse as a pem
