### ISSUE TITLE
Custom secrets?

### ISSUE THREAD

**Issue by nomeelnoj** [joe-elliott/cert-exporter#9]
Running into a weird issue where this exporter is not pulling in our own secrets.  We manage client certs outside of cert manager for connecting to different external resources and we keep them in secrets in k8s.

I have added `- --secrets-label-selector=monitor-cert`

And the secrets have:

```
metadata:
  labels:
    monitor-cert: "true"
```

Sorry if this is a dumb question, but am I missing something?

**Comment by nomeelnoj** [comment]
Sorry--that was dumb of me, I had an older version.  Upgraded to 1.3.0 and im passed that error.  I see the following in the logs:

```I0320 01:33:50.622650       1 main.go:52] Application Starting
I0320 01:33:50.627346       1 periodicSecretChecker.go:58] Begin periodic check
I0320 01:33:50.664151       1 periodicSecretChecker.go:88] Reviewing secret test-secret in test-ns
I0320 01:33:50.664165       1 periodicSecretChecker.go:97] Annotations matched.  Parsing Secret.```

However, I still do not see the metrics in prometheus.  Any light you can shed?

**Comment by nomeelnoj** [comment]
Figure this out--seems the key of the secret data has to be `*.crt`

Secret like this doesnt work:
```
apiVersion: v1
data:
  cert: LS0tLS1...
kind: Secret
metadata:
  labels:
    monitor-cert: "true"
  name: test-crt
  namespace: test-ns
type: Opaque
```
but this does work:

```
apiVersion: v1
data:
  cert.crt: LS0tLS1...
kind: Secret
metadata:
  labels:
    monitor-cert: "true"
  name: test-crt
  namespace: test-ns
type: Opaque
```
